# Generated by Django 4.0.3 on 2022-07-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0004_locationvo_closet_name_locationvo_section_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationvo',
            name='name',
        ),
    ]
