# Generated by Django 4.0.3 on 2022-07-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0005_remove_locationvo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationvo',
            name='import_href',
        ),
    ]
