# Generated by Django 4.0.3 on 2022-07-28 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_alter_shoe_bin_alter_shoe_picture_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='bin',
            new_name='binn',
        ),
    ]
