# Generated by Django 4.0.3 on 2022-07-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0005_rename_name_binvo_closet_name_rename_binn_shoe_bin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binvo',
            name='import_href',
        ),
    ]
