# Generated by Django 4.0.3 on 2022-07-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0006_remove_binvo_import_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binvo',
            name='closet_name',
            field=models.TextField(),
        ),
    ]
